pipeline {
  agent any

  stages {
    stage('GIT CLONE STAGE') {
        steps {
            git branch: 'main', url: 'https://github.com/jehadkalifah/mono-repo-test.git/'
            sh 'echo List the repository directories'
            sh 'ls -ltr'
        }
    }
    
    stage('Root Change Check') {
      when { changeset "**" }
      steps {
        sh 'echo "Root changes detected..."'
      }
    }
    
    stage('Service Common Build') {
      when { changeset "common/**" }
      steps {
        // to change the working directory to the common directory 
        // before executing the commands within it
        dir('common') {
          sh 'echo "Building common..."'
        }
      }
    }

    stage('Service 01 Build') {
      when { changeset "service01/**" }
      steps {
        dir('service01') {
          sh 'echo "Building Service01..."'
        }
      }
    }

    stage('Service 02 Build') {
      when { changeset "service02/**" }
      steps {
        dir('service02') {
          sh 'echo "Building Service02..."'
        }
      }
    }
  }
}
